/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.platform.db.routines;


import com.hedera.hashgraph.stablecoin.platform.db.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttachTablespace extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = -1397486346;

    /**
     * The parameter <code>public.attach_tablespace.tablespace</code>.
     */
    public static final Parameter<String> TABLESPACE = Internal.createParameter("tablespace", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> HYPERTABLE = Internal.createParameter("hypertable", org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""), false, false);

    /**
     * The parameter <code>public.attach_tablespace.if_not_attached</code>.
     */
    public static final Parameter<Boolean> IF_NOT_ATTACHED = Internal.createParameter("if_not_attached", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), true, false);

    /**
     * Create a new routine call instance
     */
    public AttachTablespace() {
        super("attach_tablespace", Public.PUBLIC);

        addInParameter(TABLESPACE);
        addInParameter(HYPERTABLE);
        addInParameter(IF_NOT_ATTACHED);
    }

    /**
     * Set the <code>tablespace</code> parameter IN value to the routine
     */
    public void setTablespace(String value) {
        setValue(TABLESPACE, value);
    }

    /**
     * Set the <code>hypertable</code> parameter IN value to the routine
     */
    public void setHypertable(Object value) {
        setValue(HYPERTABLE, value);
    }

    /**
     * Set the <code>if_not_attached</code> parameter IN value to the routine
     */
    public void setIfNotAttached(Boolean value) {
        setValue(IF_NOT_ATTACHED, value);
    }
}
