/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.platform.db.routines;


import com.hedera.hashgraph.stablecoin.platform.db.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;



/**
 * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
 */
@java.lang.Deprecated
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DecompressChunk extends AbstractRoutine<Object> {

    private static final long serialVersionUID = -1160840593;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""), false, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> UNCOMPRESSED_CHUNK = Internal.createParameter("uncompressed_chunk", org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""), false, false);

    /**
     * The parameter <code>public.decompress_chunk.if_compressed</code>.
     */
    public static final Parameter<Boolean> IF_COMPRESSED = Internal.createParameter("if_compressed", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), true, false);

    /**
     * Create a new routine call instance
     */
    public DecompressChunk() {
        super("decompress_chunk", Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""));

        setReturnParameter(RETURN_VALUE);
        addInParameter(UNCOMPRESSED_CHUNK);
        addInParameter(IF_COMPRESSED);
    }

    /**
     * Set the <code>uncompressed_chunk</code> parameter IN value to the routine
     */
    public void setUncompressedChunk(Object value) {
        setValue(UNCOMPRESSED_CHUNK, value);
    }

    /**
     * Set the <code>uncompressed_chunk</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setUncompressedChunk(Field<Object> field) {
        setField(UNCOMPRESSED_CHUNK, field);
    }

    /**
     * Set the <code>if_compressed</code> parameter IN value to the routine
     */
    public void setIfCompressed(Boolean value) {
        setValue(IF_COMPRESSED, value);
    }

    /**
     * Set the <code>if_compressed</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setIfCompressed(Field<Boolean> field) {
        setField(IF_COMPRESSED, field);
    }
}
