/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.platform.db.routines;


import com.hedera.hashgraph.stablecoin.platform.db.Public;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoveChunk extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1552731840;

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> CHUNK = Internal.createParameter("chunk", org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""), false, false);

    /**
     * The parameter <code>public.move_chunk.destination_tablespace</code>.
     */
    public static final Parameter<String> DESTINATION_TABLESPACE = Internal.createParameter("destination_tablespace", org.jooq.impl.SQLDataType.VARCHAR, false, false);

    /**
     * The parameter <code>public.move_chunk.index_destination_tablespace</code>.
     */
    public static final Parameter<String> INDEX_DESTINATION_TABLESPACE = Internal.createParameter("index_destination_tablespace", org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("NULL::name", org.jooq.impl.SQLDataType.VARCHAR)), true, false);

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator configuration.
     */
    @java.lang.Deprecated
    public static final Parameter<Object> REORDER_INDEX = Internal.createParameter("reorder_index", org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\"").defaultValue(org.jooq.impl.DSL.field("NULL::regclass", org.jooq.impl.SQLDataType.OTHER)), true, false);

    /**
     * The parameter <code>public.move_chunk.verbose</code>.
     */
    public static final Parameter<Boolean> VERBOSE = Internal.createParameter("verbose", org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)), true, false);

    /**
     * Create a new routine call instance
     */
    public MoveChunk() {
        super("move_chunk", Public.PUBLIC);

        addInParameter(CHUNK);
        addInParameter(DESTINATION_TABLESPACE);
        addInParameter(INDEX_DESTINATION_TABLESPACE);
        addInParameter(REORDER_INDEX);
        addInParameter(VERBOSE);
    }

    /**
     * Set the <code>chunk</code> parameter IN value to the routine
     */
    public void setChunk(Object value) {
        setValue(CHUNK, value);
    }

    /**
     * Set the <code>destination_tablespace</code> parameter IN value to the routine
     */
    public void setDestinationTablespace(String value) {
        setValue(DESTINATION_TABLESPACE, value);
    }

    /**
     * Set the <code>index_destination_tablespace</code> parameter IN value to the routine
     */
    public void setIndexDestinationTablespace(String value) {
        setValue(INDEX_DESTINATION_TABLESPACE, value);
    }

    /**
     * Set the <code>reorder_index</code> parameter IN value to the routine
     */
    public void setReorderIndex(Object value) {
        setValue(REORDER_INDEX, value);
    }

    /**
     * Set the <code>verbose</code> parameter IN value to the routine
     */
    public void setVerbose(Boolean value) {
        setValue(VERBOSE, value);
    }
}
