/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.platform.db.routines;


import com.hedera.hashgraph.stablecoin.platform.db.Public;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeBucketGapfill3 extends AbstractRoutine<Long> {

    private static final long serialVersionUID = 281067103;

    /**
     * The parameter <code>public.time_bucket_gapfill.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>public.time_bucket_gapfill.bucket_width</code>.
     */
    public static final Parameter<Long> BUCKET_WIDTH = Internal.createParameter("bucket_width", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>public.time_bucket_gapfill.ts</code>.
     */
    public static final Parameter<Long> TS = Internal.createParameter("ts", org.jooq.impl.SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>public.time_bucket_gapfill.start</code>.
     */
    public static final Parameter<Long> START = Internal.createParameter("start", org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.field("NULL::bigint", org.jooq.impl.SQLDataType.BIGINT)), true, false);

    /**
     * The parameter <code>public.time_bucket_gapfill.finish</code>.
     */
    public static final Parameter<Long> FINISH = Internal.createParameter("finish", org.jooq.impl.SQLDataType.BIGINT.defaultValue(org.jooq.impl.DSL.field("NULL::bigint", org.jooq.impl.SQLDataType.BIGINT)), true, false);

    /**
     * Create a new routine call instance
     */
    public TimeBucketGapfill3() {
        super("time_bucket_gapfill", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(BUCKET_WIDTH);
        addInParameter(TS);
        addInParameter(START);
        addInParameter(FINISH);
        setOverloaded(true);
    }

    /**
     * Set the <code>bucket_width</code> parameter IN value to the routine
     */
    public void setBucketWidth(Long value) {
        setValue(BUCKET_WIDTH, value);
    }

    /**
     * Set the <code>bucket_width</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setBucketWidth(Field<Long> field) {
        setField(BUCKET_WIDTH, field);
    }

    /**
     * Set the <code>ts</code> parameter IN value to the routine
     */
    public void setTs(Long value) {
        setValue(TS, value);
    }

    /**
     * Set the <code>ts</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setTs(Field<Long> field) {
        setField(TS, field);
    }

    /**
     * Set the <code>start</code> parameter IN value to the routine
     */
    public void setStart(Long value) {
        setValue(START, value);
    }

    /**
     * Set the <code>start</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setStart(Field<Long> field) {
        setField(START, field);
    }

    /**
     * Set the <code>finish</code> parameter IN value to the routine
     */
    public void setFinish(Long value) {
        setValue(FINISH, value);
    }

    /**
     * Set the <code>finish</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setFinish(Field<Long> field) {
        setField(FINISH, field);
    }
}
