/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.platform.db.tables;


import com.hedera.hashgraph.stablecoin.platform.db.Public;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreateHypertable extends TableImpl<Record> {

    private static final long serialVersionUID = -360326352;

    /**
     * The reference instance of <code>public.create_hypertable</code>
     */
    public static final CreateHypertable CREATE_HYPERTABLE = new CreateHypertable();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.create_hypertable.hypertable_id</code>.
     */
    public final TableField<Record, Integer> HYPERTABLE_ID = createField(DSL.name("hypertable_id"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.create_hypertable.schema_name</code>.
     */
    public final TableField<Record, String> SCHEMA_NAME = createField(DSL.name("schema_name"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.create_hypertable.table_name</code>.
     */
    public final TableField<Record, String> TABLE_NAME = createField(DSL.name("table_name"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.create_hypertable.created</code>.
     */
    public final TableField<Record, Boolean> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.BOOLEAN, this, "");

    /**
     * Create a <code>public.create_hypertable</code> table reference
     */
    public CreateHypertable() {
        this(DSL.name("create_hypertable"), null);
    }

    /**
     * Create an aliased <code>public.create_hypertable</code> table reference
     */
    public CreateHypertable(String alias) {
        this(DSL.name(alias), CREATE_HYPERTABLE);
    }

    /**
     * Create an aliased <code>public.create_hypertable</code> table reference
     */
    public CreateHypertable(Name alias) {
        this(alias, CREATE_HYPERTABLE);
    }

    private CreateHypertable(Name alias, Table<Record> aliased) {
        this(alias, aliased, new Field[14]);
    }

    private CreateHypertable(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    public <O extends Record> CreateHypertable(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, CREATE_HYPERTABLE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public CreateHypertable as(String alias) {
        return new CreateHypertable(DSL.name(alias), this, parameters);
    }

    @Override
    public CreateHypertable as(Name alias) {
        return new CreateHypertable(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public CreateHypertable rename(String name) {
        return new CreateHypertable(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public CreateHypertable rename(Name name) {
        return new CreateHypertable(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public CreateHypertable call(Object mainTable, String timeColumnName, String partitioningColumn, Integer numberPartitions, String associatedSchemaName, String associatedTablePrefix, Object chunkTimeInterval, Boolean createDefaultIndexes, Boolean ifNotExists, String partitioningFunc, Boolean migrateData, String chunkTargetSize, String chunkSizingFunc, String timePartitioningFunc) {
        return new CreateHypertable(DSL.name(getName()), null, new Field[] { 
              DSL.val(mainTable, org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""))
            , DSL.val(timeColumnName, org.jooq.impl.SQLDataType.VARCHAR)
            , DSL.val(partitioningColumn, org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("NULL::name", org.jooq.impl.SQLDataType.VARCHAR)))
            , DSL.val(numberPartitions, org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("NULL::integer", org.jooq.impl.SQLDataType.INTEGER)))
            , DSL.val(associatedSchemaName, org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("NULL::name", org.jooq.impl.SQLDataType.VARCHAR)))
            , DSL.val(associatedTablePrefix, org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("NULL::name", org.jooq.impl.SQLDataType.VARCHAR)))
            , DSL.val(chunkTimeInterval, org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"anyelement\"").defaultValue(org.jooq.impl.DSL.field("NULL::bigint", org.jooq.impl.SQLDataType.OTHER)))
            , DSL.val(createDefaultIndexes, org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("true", org.jooq.impl.SQLDataType.BOOLEAN)))
            , DSL.val(ifNotExists, org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)))
            , DSL.val(partitioningFunc, org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("NULL::regproc", org.jooq.impl.SQLDataType.VARCHAR)))
            , DSL.val(migrateData, org.jooq.impl.SQLDataType.BOOLEAN.defaultValue(org.jooq.impl.DSL.field("false", org.jooq.impl.SQLDataType.BOOLEAN)))
            , DSL.val(chunkTargetSize, org.jooq.impl.SQLDataType.CLOB.defaultValue(org.jooq.impl.DSL.field("NULL::text", org.jooq.impl.SQLDataType.CLOB)))
            , DSL.val(chunkSizingFunc, org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("'_timescaledb_internal.calculate_chunk_interval'::regproc", org.jooq.impl.SQLDataType.VARCHAR)))
            , DSL.val(timePartitioningFunc, org.jooq.impl.SQLDataType.VARCHAR.defaultValue(org.jooq.impl.DSL.field("NULL::regproc", org.jooq.impl.SQLDataType.VARCHAR)))
        });
    }

    /**
     * Call this table-valued function
     */
    public CreateHypertable call(Field<Object> mainTable, Field<String> timeColumnName, Field<String> partitioningColumn, Field<Integer> numberPartitions, Field<String> associatedSchemaName, Field<String> associatedTablePrefix, Field<Object> chunkTimeInterval, Field<Boolean> createDefaultIndexes, Field<Boolean> ifNotExists, Field<String> partitioningFunc, Field<Boolean> migrateData, Field<String> chunkTargetSize, Field<String> chunkSizingFunc, Field<String> timePartitioningFunc) {
        return new CreateHypertable(DSL.name(getName()), null, new Field[] { 
              mainTable
            , timeColumnName
            , partitioningColumn
            , numberPartitions
            , associatedSchemaName
            , associatedTablePrefix
            , chunkTimeInterval
            , createDefaultIndexes
            , ifNotExists
            , partitioningFunc
            , migrateData
            , chunkTargetSize
            , chunkSizingFunc
            , timePartitioningFunc
        });
    }
}
