/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.platform.db.tables;


import com.hedera.hashgraph.stablecoin.platform.db.Public;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class HypertableRelationSizePretty extends TableImpl<Record> {

    private static final long serialVersionUID = -1931609390;

    /**
     * The reference instance of <code>public.hypertable_relation_size_pretty</code>
     */
    public static final HypertableRelationSizePretty HYPERTABLE_RELATION_SIZE_PRETTY = new HypertableRelationSizePretty();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.hypertable_relation_size_pretty.table_size</code>.
     */
    public final TableField<Record, String> TABLE_SIZE = createField(DSL.name("table_size"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.hypertable_relation_size_pretty.index_size</code>.
     */
    public final TableField<Record, String> INDEX_SIZE = createField(DSL.name("index_size"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.hypertable_relation_size_pretty.toast_size</code>.
     */
    public final TableField<Record, String> TOAST_SIZE = createField(DSL.name("toast_size"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.hypertable_relation_size_pretty.total_size</code>.
     */
    public final TableField<Record, String> TOTAL_SIZE = createField(DSL.name("total_size"), org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>public.hypertable_relation_size_pretty</code> table reference
     */
    public HypertableRelationSizePretty() {
        this(DSL.name("hypertable_relation_size_pretty"), null);
    }

    /**
     * Create an aliased <code>public.hypertable_relation_size_pretty</code> table reference
     */
    public HypertableRelationSizePretty(String alias) {
        this(DSL.name(alias), HYPERTABLE_RELATION_SIZE_PRETTY);
    }

    /**
     * Create an aliased <code>public.hypertable_relation_size_pretty</code> table reference
     */
    public HypertableRelationSizePretty(Name alias) {
        this(alias, HYPERTABLE_RELATION_SIZE_PRETTY);
    }

    private HypertableRelationSizePretty(Name alias, Table<Record> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private HypertableRelationSizePretty(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    public <O extends Record> HypertableRelationSizePretty(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, HYPERTABLE_RELATION_SIZE_PRETTY);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public HypertableRelationSizePretty as(String alias) {
        return new HypertableRelationSizePretty(DSL.name(alias), this, parameters);
    }

    @Override
    public HypertableRelationSizePretty as(Name alias) {
        return new HypertableRelationSizePretty(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public HypertableRelationSizePretty rename(String name) {
        return new HypertableRelationSizePretty(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public HypertableRelationSizePretty rename(Name name) {
        return new HypertableRelationSizePretty(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public HypertableRelationSizePretty call(Object mainTable) {
        return new HypertableRelationSizePretty(DSL.name(getName()), null, new Field[] { 
              DSL.val(mainTable, org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""))
        });
    }

    /**
     * Call this table-valued function
     */
    public HypertableRelationSizePretty call(Field<Object> mainTable) {
        return new HypertableRelationSizePretty(DSL.name(getName()), null, new Field[] { 
              mainTable
        });
    }
}
