/*
 * This file is generated by jOOQ.
 */
package com.hedera.hashgraph.stablecoin.platform.db.tables;


import com.hedera.hashgraph.stablecoin.platform.db.Public;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShowTablespaces extends TableImpl<Record> {

    private static final long serialVersionUID = 842089600;

    /**
     * The reference instance of <code>public.show_tablespaces</code>
     */
    public static final ShowTablespaces SHOW_TABLESPACES = new ShowTablespaces();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>public.show_tablespaces.show_tablespaces</code>.
     */
    public final TableField<Record, String> SHOW_TABLESPACES_ = createField(DSL.name("show_tablespaces"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.show_tablespaces</code> table reference
     */
    public ShowTablespaces() {
        this(DSL.name("show_tablespaces"), null);
    }

    /**
     * Create an aliased <code>public.show_tablespaces</code> table reference
     */
    public ShowTablespaces(String alias) {
        this(DSL.name(alias), SHOW_TABLESPACES);
    }

    /**
     * Create an aliased <code>public.show_tablespaces</code> table reference
     */
    public ShowTablespaces(Name alias) {
        this(alias, SHOW_TABLESPACES);
    }

    private ShowTablespaces(Name alias, Table<Record> aliased) {
        this(alias, aliased, new Field[1]);
    }

    private ShowTablespaces(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function());
    }

    public <O extends Record> ShowTablespaces(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, SHOW_TABLESPACES);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public ShowTablespaces as(String alias) {
        return new ShowTablespaces(DSL.name(alias), this, parameters);
    }

    @Override
    public ShowTablespaces as(Name alias) {
        return new ShowTablespaces(alias, this, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public ShowTablespaces rename(String name) {
        return new ShowTablespaces(DSL.name(name), null, parameters);
    }

    /**
     * Rename this table
     */
    @Override
    public ShowTablespaces rename(Name name) {
        return new ShowTablespaces(name, null, parameters);
    }

    /**
     * Call this table-valued function
     */
    public ShowTablespaces call(Object hypertable) {
        return new ShowTablespaces(DSL.name(getName()), null, new Field[] { 
              DSL.val(hypertable, org.jooq.impl.DefaultDataType.getDefaultDataType("\"pg_catalog\".\"regclass\""))
        });
    }

    /**
     * Call this table-valued function
     */
    public ShowTablespaces call(Field<Object> hypertable) {
        return new ShowTablespaces(DSL.name(getName()), null, new Field[] { 
              hypertable
        });
    }
}
